name: build
run-name: Build devcontainer

on:
  push:
    # branches:
    #   - main
    # paths:
    #   - makefile
  pull_request:
    branches:
      - main
    paths:
      - makefile

jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.version_check.outputs.version_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the last two commits

      - name: Check if version has been changed
        id: version_check
        run: |
          current_version=$(grep DEVCONTAINER_VERSION= makefile | cut -d '=' -f2)
          previous_version=$(git show HEAD^:makefile | grep DEVCONTAINER_VERSION= | cut -d '=' -f2)
          if [ "$current_version" != "$previous_version" ]; then
            echo "version_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "version_changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: version_check output
        run: echo "The count was ${{ steps.version_check.outputs.version_changed }}"


  build:
    runs-on: ubuntu-latest
    needs: check_version
    if: needs.check_version.outputs.version_changed == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: version_check output
        run: echo ${{ needs.check_version.outputs.version_changed }}

      - name: version_check output
        run: echo ${{ needs.check_version.outputs.version_changed == 'true' }}

      - name: Make
        run: make build
